# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\QT\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = D:\QT\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\danie\OneDrive\Desktop\GameLauncher---QT-CPP-App-TCP\Wisielec

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\danie\OneDrive\Desktop\GameLauncher---QT-CPP-App-TCP\Wisielec

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:\QT\Tools\CMake_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\QT\Tools\CMake_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\danie\OneDrive\Desktop\GameLauncher---QT-CPP-App-TCP\Wisielec\CMakeFiles C:\Users\danie\OneDrive\Desktop\GameLauncher---QT-CPP-App-TCP\Wisielec\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\danie\OneDrive\Desktop\GameLauncher---QT-CPP-App-TCP\Wisielec\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MultiGameLauncher

# Build rule for target.
MultiGameLauncher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MultiGameLauncher
.PHONY : MultiGameLauncher

# fast build rule for target.
MultiGameLauncher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/build
.PHONY : MultiGameLauncher/fast

#=============================================================================
# Target rules for targets named MultiGameLauncher_autogen_timestamp_deps

# Build rule for target.
MultiGameLauncher_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MultiGameLauncher_autogen_timestamp_deps
.PHONY : MultiGameLauncher_autogen_timestamp_deps

# fast build rule for target.
MultiGameLauncher_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher_autogen_timestamp_deps.dir\build.make CMakeFiles/MultiGameLauncher_autogen_timestamp_deps.dir/build
.PHONY : MultiGameLauncher_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MultiGameLauncher_autogen

# Build rule for target.
MultiGameLauncher_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MultiGameLauncher_autogen
.PHONY : MultiGameLauncher_autogen

# fast build rule for target.
MultiGameLauncher_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher_autogen.dir\build.make CMakeFiles/MultiGameLauncher_autogen.dir/build
.PHONY : MultiGameLauncher_autogen/fast

MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.obj: MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.obj
.PHONY : MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.obj

# target to build an object file
MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.obj
.PHONY : MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.obj

MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.i: MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.i
.PHONY : MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.i

# target to preprocess a source file
MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.i
.PHONY : MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.i

MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.s: MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.s
.PHONY : MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.s

# target to generate assembly for a file
MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.s
.PHONY : MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.cpp.s

MultiGameLauncher_autogen/mocs_compilation.obj: MultiGameLauncher_autogen/mocs_compilation.cpp.obj
.PHONY : MultiGameLauncher_autogen/mocs_compilation.obj

# target to build an object file
MultiGameLauncher_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/MultiGameLauncher_autogen/mocs_compilation.cpp.obj
.PHONY : MultiGameLauncher_autogen/mocs_compilation.cpp.obj

MultiGameLauncher_autogen/mocs_compilation.i: MultiGameLauncher_autogen/mocs_compilation.cpp.i
.PHONY : MultiGameLauncher_autogen/mocs_compilation.i

# target to preprocess a source file
MultiGameLauncher_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/MultiGameLauncher_autogen/mocs_compilation.cpp.i
.PHONY : MultiGameLauncher_autogen/mocs_compilation.cpp.i

MultiGameLauncher_autogen/mocs_compilation.s: MultiGameLauncher_autogen/mocs_compilation.cpp.s
.PHONY : MultiGameLauncher_autogen/mocs_compilation.s

# target to generate assembly for a file
MultiGameLauncher_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/MultiGameLauncher_autogen/mocs_compilation.cpp.s
.PHONY : MultiGameLauncher_autogen/mocs_compilation.cpp.s

Wisielec_Window.obj: Wisielec_Window.cpp.obj
.PHONY : Wisielec_Window.obj

# target to build an object file
Wisielec_Window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/Wisielec_Window.cpp.obj
.PHONY : Wisielec_Window.cpp.obj

Wisielec_Window.i: Wisielec_Window.cpp.i
.PHONY : Wisielec_Window.i

# target to preprocess a source file
Wisielec_Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/Wisielec_Window.cpp.i
.PHONY : Wisielec_Window.cpp.i

Wisielec_Window.s: Wisielec_Window.cpp.s
.PHONY : Wisielec_Window.s

# target to generate assembly for a file
Wisielec_Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/Wisielec_Window.cpp.s
.PHONY : Wisielec_Window.cpp.s

boardscene.obj: boardscene.cpp.obj
.PHONY : boardscene.obj

# target to build an object file
boardscene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/boardscene.cpp.obj
.PHONY : boardscene.cpp.obj

boardscene.i: boardscene.cpp.i
.PHONY : boardscene.i

# target to preprocess a source file
boardscene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/boardscene.cpp.i
.PHONY : boardscene.cpp.i

boardscene.s: boardscene.cpp.s
.PHONY : boardscene.s

# target to generate assembly for a file
boardscene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/boardscene.cpp.s
.PHONY : boardscene.cpp.s

chinczyk_network.obj: chinczyk_network.cpp.obj
.PHONY : chinczyk_network.obj

# target to build an object file
chinczyk_network.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/chinczyk_network.cpp.obj
.PHONY : chinczyk_network.cpp.obj

chinczyk_network.i: chinczyk_network.cpp.i
.PHONY : chinczyk_network.i

# target to preprocess a source file
chinczyk_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/chinczyk_network.cpp.i
.PHONY : chinczyk_network.cpp.i

chinczyk_network.s: chinczyk_network.cpp.s
.PHONY : chinczyk_network.s

# target to generate assembly for a file
chinczyk_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/chinczyk_network.cpp.s
.PHONY : chinczyk_network.cpp.s

chinczyk_window.obj: chinczyk_window.cpp.obj
.PHONY : chinczyk_window.obj

# target to build an object file
chinczyk_window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/chinczyk_window.cpp.obj
.PHONY : chinczyk_window.cpp.obj

chinczyk_window.i: chinczyk_window.cpp.i
.PHONY : chinczyk_window.i

# target to preprocess a source file
chinczyk_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/chinczyk_window.cpp.i
.PHONY : chinczyk_window.cpp.i

chinczyk_window.s: chinczyk_window.cpp.s
.PHONY : chinczyk_window.s

# target to generate assembly for a file
chinczyk_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/chinczyk_window.cpp.s
.PHONY : chinczyk_window.cpp.s

game_logic.obj: game_logic.cpp.obj
.PHONY : game_logic.obj

# target to build an object file
game_logic.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/game_logic.cpp.obj
.PHONY : game_logic.cpp.obj

game_logic.i: game_logic.cpp.i
.PHONY : game_logic.i

# target to preprocess a source file
game_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/game_logic.cpp.i
.PHONY : game_logic.cpp.i

game_logic.s: game_logic.cpp.s
.PHONY : game_logic.s

# target to generate assembly for a file
game_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/game_logic.cpp.s
.PHONY : game_logic.cpp.s

gra.obj: gra.cpp.obj
.PHONY : gra.obj

# target to build an object file
gra.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/gra.cpp.obj
.PHONY : gra.cpp.obj

gra.i: gra.cpp.i
.PHONY : gra.i

# target to preprocess a source file
gra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/gra.cpp.i
.PHONY : gra.cpp.i

gra.s: gra.cpp.s
.PHONY : gra.s

# target to generate assembly for a file
gra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/gra.cpp.s
.PHONY : gra.cpp.s

gracz.obj: gracz.cpp.obj
.PHONY : gracz.obj

# target to build an object file
gracz.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/gracz.cpp.obj
.PHONY : gracz.cpp.obj

gracz.i: gracz.cpp.i
.PHONY : gracz.i

# target to preprocess a source file
gracz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/gracz.cpp.i
.PHONY : gracz.cpp.i

gracz.s: gracz.cpp.s
.PHONY : gracz.s

# target to generate assembly for a file
gracz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/gracz.cpp.s
.PHONY : gracz.cpp.s

kosci_logic.obj: kosci_logic.cpp.obj
.PHONY : kosci_logic.obj

# target to build an object file
kosci_logic.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_logic.cpp.obj
.PHONY : kosci_logic.cpp.obj

kosci_logic.i: kosci_logic.cpp.i
.PHONY : kosci_logic.i

# target to preprocess a source file
kosci_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_logic.cpp.i
.PHONY : kosci_logic.cpp.i

kosci_logic.s: kosci_logic.cpp.s
.PHONY : kosci_logic.s

# target to generate assembly for a file
kosci_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_logic.cpp.s
.PHONY : kosci_logic.cpp.s

kosci_network.obj: kosci_network.cpp.obj
.PHONY : kosci_network.obj

# target to build an object file
kosci_network.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_network.cpp.obj
.PHONY : kosci_network.cpp.obj

kosci_network.i: kosci_network.cpp.i
.PHONY : kosci_network.i

# target to preprocess a source file
kosci_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_network.cpp.i
.PHONY : kosci_network.cpp.i

kosci_network.s: kosci_network.cpp.s
.PHONY : kosci_network.s

# target to generate assembly for a file
kosci_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_network.cpp.s
.PHONY : kosci_network.cpp.s

kosci_window.obj: kosci_window.cpp.obj
.PHONY : kosci_window.obj

# target to build an object file
kosci_window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_window.cpp.obj
.PHONY : kosci_window.cpp.obj

kosci_window.i: kosci_window.cpp.i
.PHONY : kosci_window.i

# target to preprocess a source file
kosci_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_window.cpp.i
.PHONY : kosci_window.cpp.i

kosci_window.s: kosci_window.cpp.s
.PHONY : kosci_window.s

# target to generate assembly for a file
kosci_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kosci_window.cpp.s
.PHONY : kosci_window.cpp.s

kostka.obj: kostka.cpp.obj
.PHONY : kostka.obj

# target to build an object file
kostka.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kostka.cpp.obj
.PHONY : kostka.cpp.obj

kostka.i: kostka.cpp.i
.PHONY : kostka.i

# target to preprocess a source file
kostka.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kostka.cpp.i
.PHONY : kostka.cpp.i

kostka.s: kostka.cpp.s
.PHONY : kostka.s

# target to generate assembly for a file
kostka.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/kostka.cpp.s
.PHONY : kostka.cpp.s

launcher.obj: launcher.cpp.obj
.PHONY : launcher.obj

# target to build an object file
launcher.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/launcher.cpp.obj
.PHONY : launcher.cpp.obj

launcher.i: launcher.cpp.i
.PHONY : launcher.i

# target to preprocess a source file
launcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/launcher.cpp.i
.PHONY : launcher.cpp.i

launcher.s: launcher.cpp.s
.PHONY : launcher.s

# target to generate assembly for a file
launcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/launcher.cpp.s
.PHONY : launcher.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/main.cpp.s
.PHONY : main.cpp.s

pionek.obj: pionek.cpp.obj
.PHONY : pionek.obj

# target to build an object file
pionek.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/pionek.cpp.obj
.PHONY : pionek.cpp.obj

pionek.i: pionek.cpp.i
.PHONY : pionek.i

# target to preprocess a source file
pionek.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/pionek.cpp.i
.PHONY : pionek.cpp.i

pionek.s: pionek.cpp.s
.PHONY : pionek.s

# target to generate assembly for a file
pionek.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/pionek.cpp.s
.PHONY : pionek.cpp.s

plansza.obj: plansza.cpp.obj
.PHONY : plansza.obj

# target to build an object file
plansza.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/plansza.cpp.obj
.PHONY : plansza.cpp.obj

plansza.i: plansza.cpp.i
.PHONY : plansza.i

# target to preprocess a source file
plansza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/plansza.cpp.i
.PHONY : plansza.cpp.i

plansza.s: plansza.cpp.s
.PHONY : plansza.s

# target to generate assembly for a file
plansza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/plansza.cpp.s
.PHONY : plansza.cpp.s

tokenitem.obj: tokenitem.cpp.obj
.PHONY : tokenitem.obj

# target to build an object file
tokenitem.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/tokenitem.cpp.obj
.PHONY : tokenitem.cpp.obj

tokenitem.i: tokenitem.cpp.i
.PHONY : tokenitem.i

# target to preprocess a source file
tokenitem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/tokenitem.cpp.i
.PHONY : tokenitem.cpp.i

tokenitem.s: tokenitem.cpp.s
.PHONY : tokenitem.s

# target to generate assembly for a file
tokenitem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MultiGameLauncher.dir\build.make CMakeFiles/MultiGameLauncher.dir/tokenitem.cpp.s
.PHONY : tokenitem.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... MultiGameLauncher_autogen
	@echo ... MultiGameLauncher_autogen_timestamp_deps
	@echo ... MultiGameLauncher
	@echo ... MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.obj
	@echo ... MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.i
	@echo ... MultiGameLauncher_autogen/EWIEGA46WW/qrc_zasoby.s
	@echo ... MultiGameLauncher_autogen/mocs_compilation.obj
	@echo ... MultiGameLauncher_autogen/mocs_compilation.i
	@echo ... MultiGameLauncher_autogen/mocs_compilation.s
	@echo ... Wisielec_Window.obj
	@echo ... Wisielec_Window.i
	@echo ... Wisielec_Window.s
	@echo ... boardscene.obj
	@echo ... boardscene.i
	@echo ... boardscene.s
	@echo ... chinczyk_network.obj
	@echo ... chinczyk_network.i
	@echo ... chinczyk_network.s
	@echo ... chinczyk_window.obj
	@echo ... chinczyk_window.i
	@echo ... chinczyk_window.s
	@echo ... game_logic.obj
	@echo ... game_logic.i
	@echo ... game_logic.s
	@echo ... gra.obj
	@echo ... gra.i
	@echo ... gra.s
	@echo ... gracz.obj
	@echo ... gracz.i
	@echo ... gracz.s
	@echo ... kosci_logic.obj
	@echo ... kosci_logic.i
	@echo ... kosci_logic.s
	@echo ... kosci_network.obj
	@echo ... kosci_network.i
	@echo ... kosci_network.s
	@echo ... kosci_window.obj
	@echo ... kosci_window.i
	@echo ... kosci_window.s
	@echo ... kostka.obj
	@echo ... kostka.i
	@echo ... kostka.s
	@echo ... launcher.obj
	@echo ... launcher.i
	@echo ... launcher.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... pionek.obj
	@echo ... pionek.i
	@echo ... pionek.s
	@echo ... plansza.obj
	@echo ... plansza.i
	@echo ... plansza.s
	@echo ... tokenitem.obj
	@echo ... tokenitem.i
	@echo ... tokenitem.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

